# Generated by Django 5.2.17 on 2026-09-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_rename_sku_codigo_categorias'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrelativoCodigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=20, unique=True)),
                ('ultimo', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Correlativo de código',
                'verbose_name_plural': 'Correlativos de código',
            },
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(blank=True, help_text='Se genera automáticamente según la categoría.', max_length=50, unique=True, verbose_name='Código'),
        ),
    ]
