# Generated by Django 5.2.17 on 2026-09-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_correlativocodigo_alter_producto_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinventario',
            name='motivo',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
