# Generated by Django 5.2.17 on 2026-09-17 18:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_movimientoinventario_motivo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='movimientoinventario',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='movimiento_cantidad_positiva'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(condition=models.Q(('stock_actual__gte', 0)), name='producto_stock_actual_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(condition=models.Q(('stock_minimo__gte', 0)), name='producto_stock_minimo_no_negativo'),
        ),
    ]
