# Generated by Django 5.2.17 on 2026-09-12 02:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAlimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('proteina_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Proteína (%)')),
                ('proveedor', models.CharField(blank=True, max_length=200)),
                ('costo_por_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de alimento',
                'verbose_name_plural': 'Tipos de alimento',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAlimentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cantidad_servida_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cantidad_sobrante_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_alimentacion', to='registro.lote')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tipo_alimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alimentos.tipoalimento')),
            ],
            options={
                'verbose_name': 'Registro de alimentación',
                'verbose_name_plural': 'Registros de alimentación',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='PlanAlimentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_diaria_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('etapa', models.CharField(choices=[('destete', 'Destete'), ('crecimiento', 'Crecimiento'), ('engorde', 'Engorde'), ('gestacion', 'Gestación'), ('lactancia', 'Lactancia')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_alimentacion', to='registro.lote')),
                ('tipo_alimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alimentos.tipoalimento')),
            ],
            options={
                'verbose_name': 'Plan de alimentación',
                'verbose_name_plural': 'Planes de alimentación',
                'ordering': ['lote', 'etapa'],
            },
        ),
    ]
