# Generated by Django 5.2.17 on 2026-09-12 02:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Padrillo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('raza', models.CharField(max_length=100)),
                ('origen', models.CharField(choices=[('interno', 'Interno'), ('externo', 'Externo')], default='interno', max_length=20)),
                ('stock_pajuelas', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Padrillo',
                'verbose_name_plural': 'Padrillos',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Inseminacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('natural', 'Natural'), ('artificial', 'Artificial')], max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cerda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inseminaciones', to='registro.cerdo')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('padrillo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inseminacion.padrillo')),
            ],
            options={
                'verbose_name': 'Inseminación',
                'verbose_name_plural': 'Inseminaciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticoPrenez',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('resultado', models.CharField(choices=[('positivo', 'Positivo'), ('negativo', 'Negativo'), ('dudoso', 'Dudoso')], max_length=20)),
                ('metodo', models.CharField(blank=True, max_length=100)),
                ('inseminacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostico', to='inseminacion.inseminacion')),
            ],
            options={
                'verbose_name': 'Diagnóstico de preñez',
                'verbose_name_plural': 'Diagnósticos de preñez',
            },
        ),
        migrations.CreateModel(
            name='Parto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('lechones_vivos', models.PositiveIntegerField()),
                ('lechones_muertos', models.PositiveIntegerField(default=0)),
                ('lechones_destetados', models.PositiveIntegerField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('inseminacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partos', to='inseminacion.inseminacion')),
            ],
            options={
                'verbose_name': 'Parto',
                'verbose_name_plural': 'Partos',
                'ordering': ['-fecha'],
            },
        ),
    ]
