# Generated by Django 5.2.17 on 2026-09-12 02:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('intervalo_dias', models.PositiveIntegerField(blank=True, help_text='Días hasta refuerzo', null=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Vacuna',
                'verbose_name_plural': 'Vacunas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='AplicacionVacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_aplicacion', models.DateField()),
                ('dosis', models.CharField(max_length=100)),
                ('lote_medicamento', models.CharField(blank=True, max_length=100)),
                ('proxima_dosis', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cerdo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacunas', to='registro.cerdo')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('vacuna', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vacunas.vacuna')),
            ],
            options={
                'verbose_name': 'Aplicación de vacuna',
                'verbose_name_plural': 'Aplicaciones de vacuna',
                'ordering': ['-fecha_aplicacion'],
            },
        ),
    ]
