# Generated by Django 5.2.17 on 2026-09-12 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('corral', models.CharField(blank=True, max_length=100)),
                ('fecha_ingreso', models.DateField()),
                ('meta_peso', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='Cerdo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arete', models.CharField(max_length=50, unique=True, verbose_name='Arete / Código')),
                ('raza', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], max_length=1)),
                ('fecha_nacimiento', models.DateField()),
                ('peso_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('engorde', 'En engorde'), ('vendido', 'Vendido'), ('fallecido', 'Fallecido')], default='activo', max_length=20)),
                ('corral', models.CharField(blank=True, max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('madre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crias', to='registro.cerdo')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descendientes', to='registro.cerdo')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cerdos', to='registro.lote')),
            ],
            options={
                'verbose_name': 'Cerdo',
                'verbose_name_plural': 'Cerdos',
                'ordering': ['arete'],
            },
        ),
    ]
