# Generated by Django 5.2.17 on 2026-09-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrelativoArete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimo', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Correlativo de arete',
                'verbose_name_plural': 'Correlativos de arete',
            },
        ),
        migrations.AddField(
            model_name='cerdo',
            name='fecha_ingreso',
            field=models.DateField(blank=True, help_text='Dejar vacío si nació en la granja.', null=True),
        ),
        migrations.AddField(
            model_name='cerdo',
            name='nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cerdo',
            name='arete',
            field=models.CharField(blank=True, help_text='Se genera automáticamente (C-0001, C-0002...).', max_length=50, unique=True, verbose_name='Arete / Código'),
        ),
        migrations.AlterField(
            model_name='cerdo',
            name='peso_actual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Peso actual (kg)'),
        ),
        migrations.AlterField(
            model_name='cerdo',
            name='raza',
            field=models.CharField(choices=[('landrace', 'Landrace'), ('yorkshire', 'Yorkshire'), ('duroc', 'Duroc'), ('hampshire', 'Hampshire'), ('pietran', 'Pietrán'), ('berkshire', 'Berkshire'), ('cruce', 'Cruce (mestizo)'), ('criollo', 'Criollo'), ('otro', 'Otro')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='cerdo',
            constraint=models.CheckConstraint(condition=models.Q(('peso_actual__gte', 0)), name='cerdo_peso_no_negativo'),
        ),
    ]
