# Generated by Django 5.2.17 on 2026-09-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_correlativoarete_cerdo_fecha_ingreso_cerdo_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cerdo',
            name='raza_otro',
            field=models.CharField(blank=True, help_text='Completar solo si elegiste "Otro".', max_length=100, verbose_name='¿Cuál raza?'),
        ),
        migrations.AlterField(
            model_name='cerdo',
            name='estado',
            field=models.CharField(choices=[('activo', 'En granja'), ('engorde', 'En engorde'), ('vendido', 'Vendido'), ('fallecido', 'Fallecido')], default='activo', help_text='En granja: vive en la granja (crianza o reproducción). En engorde: destinado a venta para carne. Vendido/Fallecido: ya no está en la granja.', max_length=20),
        ),
    ]
