# Generated by Django 5.2.17 on 2026-09-17 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_cerdo_raza_otro_alter_cerdo_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaCerdo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('edad_min_dias', models.PositiveIntegerField(blank=True, help_text='Opcional. Referencia para saber cuándo un cerdo entra en esta categoría.', null=True, verbose_name='Edad mínima (días)')),
                ('edad_max_dias', models.PositiveIntegerField(blank=True, help_text='Opcional. Referencia para saber cuándo un cerdo sale de esta categoría.', null=True, verbose_name='Edad máxima (días)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoría de cerdo',
                'verbose_name_plural': 'Categorías de cerdos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='cerdo',
            name='estado',
            field=models.CharField(choices=[('activo', 'En granja'), ('vendido', 'Vendido'), ('fallecido', 'Fallecido')], default='activo', help_text='En granja: el animal vive en la granja. Vendido/Fallecido: ya no está en la granja.', max_length=20),
        ),
        migrations.AddField(
            model_name='cerdo',
            name='categoria',
            field=models.ForeignKey(blank=True, help_text='Etapa o función del cerdo (Lechón, Engorde, Pie de cría...).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cerdos', to='registro.categoriacerdo', verbose_name='Categoría'),
        ),
    ]
