# Generated by Django 5.2.17 on 2026-09-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0005_data_categorias_peru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cerdo',
            name='arete',
            field=models.CharField(blank=True, help_text='Se genera automáticamente (A-0001, A-0002...).', max_length=50, unique=True, verbose_name='Arete / Código'),
        ),
    ]
