# Generated by Django 5.2.17 on 2026-09-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0006_alter_cerdo_arete'),
    ]

    operations = [
        migrations.AddField(
            model_name='cerdo',
            name='fecha_salida',
            field=models.DateField(blank=True, help_text='Fecha de venta o fallecimiento (solo si ya no está en la granja).', null=True, verbose_name='Fecha de salida'),
        ),
        migrations.AddField(
            model_name='cerdo',
            name='precio_venta',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Solo si el cerdo fue vendido.', max_digits=10, null=True, verbose_name='Precio de venta (S/.)'),
        ),
        migrations.AddConstraint(
            model_name='cerdo',
            constraint=models.CheckConstraint(condition=models.Q(('precio_venta__gte', 0)), name='cerdo_precio_venta_no_negativo'),
        ),
    ]
